export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';
export const RESET_REGISTER_ERRORS = 'RESET_REGISTER_ERRORS';
export const RESET_LOGIN_ERRORS = 'RESET_LOGIN_ERRORS';



export const CART_START = 'CART_START';
export const CART_SUCCESS = 'CART_SUCCESS';
export const CART_FAIL = 'CART_FAIL';
export const CART_FETCH_FAIL = 'CART_FETCH_FAIL';
